version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5wsDNc_Yv379IV2A
      POSTGRES_DB: platform
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres-data:
    name: postgres-data-${COMPOSE_PROJECT_NAME:-default}-${TIMESTAMP:-0}

networks:
  backend: